config/routes.rb
Blog::Application.routes.draw do

	resources :users
	resources :sessions
	resources :posts do
    resources :comments
    collection do
      get :tag
    end
	end

	root :to => "posts#index"

	match "/log_in" => "sessions#new"
	match "/log_out" => "sessions#destroy"
	match "/sign_up" => "users#new"
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :content, :user_id

  validates_presence_of :content, :on => :create

  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :title, :content, :tag_list

  acts_as_taggable_on :tags

  validates_presence_of :title
  validates_presence_of :content
  validates_presence_of :user_id, :on => :create

  belongs_to :user
  has_many :comments, :dependent => :destroy

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password, :password_confirmation, :nickname
  
  attr_accessor :password
  before_save :encrypt_password
  
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
	validates_format_of :email, :with => /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i, :on => :create

  has_many :posts, :dependent => :destroy
  has_many :comments, :dependent => :destroy
  
  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def create
    post = Post.find(params[:post_id])
    @comment = post.comments.build(params[:comment])
    @comment.user_id = (!current_user.nil?) ? current_user.id : nil
    if @comment.save
      redirect_to post
    else
      redirect_to post
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def tag_cloud
    @tags = @post.tag_counts_on(:tags)
  end

  def tag
    @tag_name = params[:id]
    @posts = Post.tagged_with(params[:id]).paginate(:page => params[:page], :per_page => 5)
    render 'tags/show'
  end

  def index
    @posts = Post.paginate(:page => params[:page], :per_page => 5)
    render 'index'
  end
	
  def new
    @post = Post.new
  end
	
  def create
    @post = current_user.posts.build(params[:post])
    if @post.save
      redirect_to posts_url, :notice => "Post created!"
    else
      render 'new'
    end
  end

  def show
    @post = Post.find(params[:id])
    @user = current_user
    tag_cloud
    @comment = @post.comments.new
  end

  def destroy
    Post.find(params[:id]).destroy
    redirect_to root_url
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.authenticate(params[:email], params[:password])
    if user
	    session[:user_id] = user.id
      redirect_to posts_url, :notice => "Logged in!"
    else
      flash.now.alert = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged out!"
  end
end

app/controllers/tags_controller.rb
class TagsController
  def index
    @tags = Tag.find(:all)
  end

  def show
    @tag = Tag.find(params[:id])
    @posts = Posts.find_tagged_with(@tag).paginate(:page => params[:page], :per_page => 5)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to root_url, :notice => "Signed up!"
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    render 'show'
  end
	
  def edit
    if User.find(params[:id]) == current_user	
      @user = User.find(params[:id])
    else
      redirect_to root_url
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      redirect_to root_url, :notice => "Profile updated!"
    else
      render 'edit'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<%= form_for @comment do |f| %>
  <% if @comment.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @comment.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </p>
  <p class="button"><%= f.submit %></p>
<% end %>

app/views/comments/show.html.erb
<% @post.comments.each do |comment| %>
  <p><%= user.find(comment.user_id).email %> writes: </p>
  <p><%= comment.text %></p>
<% end %>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <% if current_user %>
        <ul class="nav">
          <li>Logged in as <%= current_user.nickname %>.</li>
          <li class="divider-vertical"></li>
          <li class="active"><%= link_to "My profile", edit_user_path(current_user) %></li>
          <li class="active"><%= link_to "Posts", posts_path %></li>
          <li class="active"><%= link_to "Create new post", new_post_path %></li>
          <li class="divider-vertical"></li>
          <li class="active pull-right"><%= link_to "Log out", log_out_path %></li>
        </ul>
      <% else %>
        <ul class="nav">
          <li class="active"><%= link_to "Sign up", sign_up_path %></li>
          <li class="active"><%= link_to "log in", log_in_path %></li>
  		  </ul>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Khodzha's first web application</title>
    <%= javascript_include_tag "application" %>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>

    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<div class="page-header">
  <h1>All posts</h1>
</div>

<%= will_paginate @posts, :renderer => BootstrapPagination::Rails %>
<br>
<% @posts.each do |post| %>
  <li>
    <div class="post">
  	  <div id="title"><%= link_to post.title, post %></div><div id="author"> by <%= link_to post.user.nickname, post.user %> <%= time_ago_in_words post.created_at %> ago</div>
      <% if !current_user.nil? && current_user.email == post.user.email %>
        <%= link_to 'Delete this post', post, :method=> :delete, confirm: "You sure?" %>
        <br>
      <% end %>
      <div id='content'><%= truncate(post.content, :length => 25, :omission => '...') %></div>
      <br>
    </div>
  </li>
<% end %>

<%= will_paginate @posts, :renderer => BootstrapPagination::Rails %>

app/views/posts/new.html.erb
<div class="page-header">
  <h1>New post</h1>
</div>

<div class="row">
  <div class="span6 offset3">
    <%= form_for @post do |f| %>
      <% if @post.errors.any? %>
        <div class="error_messages">
          <h2>Form is invalid</h2>
          <ul>
            <% for message in @post.errors.full_messages %>
            <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <p>
        <%= f.label :title %><br />
        <%= f.text_field :title %>
      </p>
      <p>
        <%= f.label "tags(separate with comma)" %><br />
        <%= f.text_field :tag_list %>
      </p>
      <p>
        <%= f.label :content %><br />
        <%= f.text_area :content, :size => '80x10' %>
      </p>
      <p class="button"><%= f.submit %></p>
    <% end %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="page-header">
  <h1><%= @post.title %></h1>
</div>

<div class="post-header">
  <p>posted by <%= link_to @post.user.nickname, @post.user %> at <%= @post.created_at %> (<%= time_ago_in_words @post.created_at %> ago)</p>
</div>

<div class="post-content">
  <%= @post.content %>
</div>

<div class="tags">
  <h5>Tags</h5>
  <% tag_cloud(@tags, %w(css1 css2 css3 css4)) do |tag, css_class| %>
    <span id="tag">
      <%= link_to tag.name, { :action => :tag, :id => tag.name }, :class => css_class %>
    </span>
  <% end %>
  <br>
</div>

<div class="comments">
  <h5>Comments (<%= pluralize(@post.comments.count, 'comment') %>)</h5>
  <% @post.comments.each do |comment| %>
    <% if !comment.created_at.nil? %>
      <% if !comment.user_id.nil? %>
        <span><%= link_to User.find(comment.user_id).nickname, User.find(comment.user_id) %> writes <%= time_ago_in_words comment.created_at%> ago:<br>
      <% else %>
        Anonymous writes <%= time_ago_in_words comment.created_at%> ago:<br>
      <% end %>
      <p><%= comment.content %></p>
    <% end %>
  <% end %>
</div>

<div class="row">
  <div class="span6 offset1">
    <%= form_for [@post, @comment] do |f| %>
      <% if @comment.errors.any? %>
        <div class="error_messages">
          <h2>Form is invalid</h2>
          <ul>
            <% for message in @comment.errors.full_messages %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <p>
        <%= f.text_field :content %>
      </p>
      <p class="button"><%= f.submit %></p>
    <% end %>
  </div>
</div>

app/views/tags/show.html.erb
<div class="page-header">
  <h1>Posts, tagged with <%= @tag_name %></h1>
</div>

<%= will_paginate @posts, :renderer => BootstrapPagination::Rails %>
<br>
<% @posts.each do |post| %>
  <li>
    <div class="post">
      <div id="title"><%= link_to post.title, post %></div><div id="author"> by <%= link_to post.user.nickname, post.user %> <%= time_ago_in_words post.created_at %> ago</div>
      <% if !current_user.nil? && current_user.email == post.user.email %>
        <%= link_to 'Delete this post', post, :method=> :delete, confirm: "You sure?" %>
        <br>
      <% end %>
      <div id='content'><%= truncate(post.content, :length => 25, :omission => '...') %></div>
      <br>
    </div>
  </li>
<% end %>
<%= will_paginate @posts, :renderer => BootstrapPagination::Rails %>

app/views/users/edit.html.erb
<div class="page-header">
  <h1>Edit your profile</h1>
</div>

<div class="row">
  <div class="span6 offset3">
    <%= form_for @user do |f| %>
      <% if @user.errors.any? %>
        <div class="error_messages">
          <h2>Form is invalid</h2>
          <ul>
            <% for message in @user.errors.full_messages %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <p>
        <%= f.label :email %><br />
        <%= f.text_field :email %>
      </p>
      <p>
        <%= f.label :nickname %><br />
        <%= f.text_field :nickname %>
      </p>
      <p>
        <%= f.label :password %><br />
        <%= f.password_field :password %>
      </p>
      <p>
        <%= f.label :password_confirmation %><br />
        <%= f.password_field :password_confirmation %>
      </p>
      <p class="button"><%= f.submit %></p>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<div class="page-header">
<h1>Sign Up</h1>
</div>
<div class="row">
  <div class="span6 offset3">
    <%= form_for @user do |f| %>
      <% if @user.errors.any? %>
        <div class="error_messages">
          <h2>Form is invalid</h2>
          <ul>
            <% for message in @user.errors.full_messages %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    <p>
      <%= f.label :email %><br />
      <%= f.text_field :email %>
    </p>
    <p>
      <%= f.label :nickname %><br />
      <%= f.text_field :nickname %>
    </p>
    <p>
      <%= f.label :password %><br />
      <%= f.password_field :password %>
    </p>
    <p>
      <%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation %>
    </p>
    <p class="button"><%= f.submit %></p>
  <% end %>

 </div>
</div>

app/views/users/show.html.erb
<div class="page-header">
  <h1>Posts of <%= @user.nickname %></h1>
</div>

<% @user.posts.each do |post| %>
  <li>
    <div class="post">
      <div id="title"><%= link_to post.title, post %></div><div id="author"> by <%= link_to post.user.nickname, post.user %> <%= time_ago_in_words post.created_at %> ago</div>
      <% if !current_user.nil? && current_user.email == post.user.email %>
        <%= link_to 'Delete this post', post, :method=> :delete, confirm: "You sure?" %>
        <br>
      <% end %>
      <div id='content'><%= truncate(post.content, :length => 25, :omission => '...') %></div>
      <br>
    </div>
  </li>
<% end %>